# Generated by Django 3.1.4 on 2021-04-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='saddr',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='student',
            name='semail',
            field=models.EmailField(max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=50),
        ),
    ]
